export { ClientDetail } from './clients/ClientDetail';
export { WellDetail } from './well/WellDetail';
export { StepperPage } from './stepper/StepperPage';
export { SandSimulator } from './simulator/SandSimulator';
export { GasSimulator } from './simulator/GasSimulator';
export { PressureSimulator } from './simulator/PressureSimulator';
export { SalesPrintPage } from './sales/SalesPrintPage';
export { LoginPage } from './LoginPage';
export { ClientPage } from './clients/ClientPage';
export { WellPage } from './well/WellPage';
export { SalesFormPage } from './sales/SalesFormPage';
export { SalesPage } from './sales/SalesPage';
export { ProductPage } from './products/ProductPage';
export { TallyDesignForm } from './tallyDesign/TallyDesignForm';
export { TallyDesignList } from './tallyDesign/TallyDesignList';
export { TechDesignList } from "./technicalDesign/TechDesignList";
export { TechDesignForm } from "./technicalDesign/TechDesignForm";
export { HomePage } from "./HomePage";

